name: Android CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    - name: Release APK
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/release/app-release.apk
          app/build/outputs/apk/debug/app-debug.apk
        body: |
          ## 加密货币钱包应用 ${{ github.ref_name }}
          
          ### 更新内容
          - 初始版本发布
          
          ### 下载
          - [下载发布版 APK](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-release.apk)
          - [下载调试版 APK](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/app-debug.apk) 